grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.zahlenhelfer.duckdns.org
    path: /
# persistence:
#   enabled: true
#   type: sts
#   storageClassName: "storageClassName"
#   accessModes:
#     - ReadWriteOnce
#   size: 20Gi
#   finalizers:
#     - kubernetes.io/pvc-protection
