apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: popeye
  namespace: argocd
spec:
  project: default
  sources:
    - chart: popeye
      repoURL: ghcr.io/deb4sh/helm-popeye
      targetRevision: 0.0.0-e7609a
      helm:
        releaseName: popeye
        valueFiles:
          - $values/apps/popeye/values.yaml
    - repoURL: https://github.com/zahlenhelfer/argocd-app-of-apps.git
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: popeye
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true # Automatically creates namespace if it doesn't exist
