apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: opencost
  sources:
    - chart: opencost
      repoURL: https://opencost.github.io/opencost-helm-chart
      targetRevision: 1.43.2
      helm:
        releaseName: opencost
        valueFiles:
          - $values/apps/kubecost/values.yaml
    - repoURL: https://github.com/zahlenhelfer/argocd-app-of-apps.git
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true # Automatically creates namespace if it doesn't exist
