opencost:
  ui:
    ingress:
      enabled: true
      ingressClassName: 'nginx'
      hosts:
        - host: 'opencost.zahlenhelfer.duckdns.org'
          paths:
            - /
  metrics:
    serviceMonitor:
      enabled: true
