opencost:
  ui:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: opencost.zahlenhelfer.duckdns.org
          paths:
            - '/'
  prometheus:
    internal:
      enabled: true
      namespaceName: monitoring
      serviceName: kube-prometheus-stack-prometheus
      port: 9090

  metrics:
    serviceMonitor:
      enabled: true
      namespace: monitoring
