opencost:
  ui:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: opencost.zahlenhelfer.duckdns.org
  prometheus:
    internal:
      enabled: true
      namespaceName: monitoring
      serviceName: kube-prometheus-stack-prometheus
  metrics:
    serviceMonitor:
      enabled: true
      namespace: monitoring
