apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.12.0
      helm:
        releaseName: ingress-nginx
        valueFiles:
          - $values/apps/ingress-nginx/values.yaml
    - repoURL: https://github.com/zahlenhelfer/argocd-app-of-apps.git
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true # Automatically creates namespace if it doesn't exist
