controller:
  ingressClassResource:
    enabled: true
    default: true
  admissionWebhooks:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      additionalLabels:
        release: prometheus
      enabled: true
  podAnnotations:
    prometheus.io/port: '10254'
    prometheus.io/scrape: 'true'
