apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: default
  sources:
    - chart: victoria-metrics-single
      repoURL: https://victoriametrics.github.io/helm-charts/
      targetRevision: 0.13.6
      helm:
        releaseName: victoria-metrics-single
        valueFiles:
          - $values/apps/victoria-metrics/values.yaml
    - repoURL: https://github.com/zahlenhelfer/argocd-app-of-apps.git
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: victoria-metrics
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true # Automatically creates namespace if it doesn't exist
      - Replace=true
