apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-pool
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: '3'
spec:
  ipAddressPools:
    - default-pool
