apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: default
  source:
    chart: falco
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 4.17.0
    helm:
      releaseName: falco
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: falco
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Automatically creates namespace if it doesn't exist
