apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook
    name: in-cluster
  project: default
  source:
    path: kustomized_helm/overlays/dev
    repoURL: https://github.com/d0-labs/argocd-app-of-apps-child-guestbook
    targetRevision: HEAD
    plugin:
      name: kustomized-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Automatically creates namespace if it doesn't exist
