apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: default
  sources:
    - chart: kyverno
      repoURL: https://kyverno.github.io/kyverno/
      targetRevision: 3.3.4
      helm:
        releaseName: kyverno
        valueFiles:
          - $values/apps/kyverno/values.yaml
    - repoURL: https://github.com/zahlenhelfer/argocd-app-of-apps.git
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kyverno
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true # Automatically creates namespace if it doesn't exist
      - Replace=true
