apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-std-policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  destination:
    namespace: kyverno-std-policies
    name: in-cluster
  project: default
  source:
    repoURL: https://github.com/zahlenhelfer/k8s-kyverno-policies.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
