apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  sources:
    - chart: csi-driver-nfs
      repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
      targetRevision: 4.9.0
      helm:
        releaseName: csi-driver-nfs
        valueFiles:
          - $values/apps/nfs-csi-driver/values.yaml
    - repoURL: https://github.com/zahlenhelfer/argocd-app-of-apps.git
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Automatically creates namespace if it doesn't exist
